# Generated by Django 4.0.5 on 2022-06-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_students_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Message',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
