# Generated by Django 4.0.5 on 2022-06-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=200)),
                ('user_lastname', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('from_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='message.user')),
                ('to_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='message.user')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='Receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='message.user'),
        ),
    ]
