# Generated by Django 4.0.5 on 2022-06-08 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0007_user_chat_alter_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
