# Generated by Django 4.0.5 on 2022-06-09 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0008_alter_message_receiver_delete_chat_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
