# Generated by Django 4.0.5 on 2022-06-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_alter_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
        ),
    ]
